%define name    apachetop
%define version 0.12.6
%define release %mkrel 6

Summary:	Utility to display Apache logs with a top-like interface
Name:		%name
Version:	%version
Release:	%release
License:	BSD
Group:		Monitoring
URL:		http://www.webta.org/projects/apachetop/
Source0:	http://www.webta.org/apachetop/%name-%version.tar.bz2
# mandrivaize default logfile
Patch1:		%name-0.12.6-logfile.patch
# support logfiles over 2GB (from Debian)
Patch2:		apachetop-0.12.5-large_logfile.patch
# gcc4.1 fixes (from Debian)
Patch3:		apachetop-0.12.6-gcc41.patch
# fix some error
Patch4:     apachetop-0.12.6-buffer_overflow.patch
BuildRequires:	ncurses-devel
BuildRequires:	m4
BuildRequires:	pcre-devel
BuildRequires:	adns-devel
BuildRequires:	readline-devel
BuildRequires:	autoconf2.5
Requires:	apache
BuildRoot:	%_tmppath/%name-%version

%description
ApacheTop: top-like display of Apache logs.

ApacheTop watches a logfile generated by Apache (in standard common or
combined logformat, although it doesn't (yet) make use of any of the extra
fields in combined) and generates human-parsable output in realtime.


%prep
%setup -q
%patch1 -p1 -b .log
%patch2 -p1 -b .large
%patch3 -p1 -b .gcc41
%patch4 -p0

%build
%configure2_5x
%make


%install
rm -rf %{buildroot}
%makeinstall

# 0.7: remove manpage, not usefull yet, read readme instead
rm %{buildroot}%{_mandir}/man1/*


%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,)
%_bindir/*
#%_mandir/man1/*
%doc AUTHORS LICENSE README ChangeLog TODO
