%define name    apachetop
%define version 0.12.5
%define release 3mdk

Summary:	Utility to display Apache logs with a top-like interface
Name:		%name
Version:	%version
Release:	%release
License:	BSD
Group:		Monitoring
URL:		http://clueful.shagged.org/apachetop/
Source0:	http://clueful.shagged.org/apachetop/files/%name-%version.tar.bz2
# mandrakeize default logfile
Patch1:		%name-0.7.logfile.patch.bz2
BuildRoot:	%_tmppath/%name-buildroot
BuildRequires:	ncurses-devel m4 pcre-devel adns-devel fam-devel readline-devel
Requires:	apache

%description
ApacheTop: top-like display of Apache logs.

ApacheTop watches a logfile generated by Apache (in standard common or
combined logformat, although it doesn't (yet) make use of any of the extra
fields in combined) and generates human-parsable output in realtime.


%prep
%setup -q
%patch1 -p1 -b .log

%build
%configure
%make


%install
if [ -d $RPM_BUILD_ROOT ]; then rm -r $RPM_BUILD_ROOT; fi
%makeinstall

# 0.7: remove manpage, not usefull yet, read readme instead
rm %{buildroot}%{_mandir}/man1/*


%clean
if [ -d $RPM_BUILD_ROOT ]; then rm -r $RPM_BUILD_ROOT; fi


%files
%defattr(-,root,root,)
%_bindir/*
#%_mandir/man1/*
%doc AUTHORS LICENSE README ChangeLog TODO
